INSERT INTO hadith_title(id, title, `next`) VALUES(0, "Les actions ne valent que par leurs intentions", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(1, "L'Islam, la foi, et la bienfaisance", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(2, "Les Piliers de l'Islam", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(3, "Les dernières œuvres sont déterminantes", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(4, "La nullité des innovations", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(5, "Le licite et l'illicite", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(6, "La religion est le bon conseil", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(7, "Le caractère sacré du Musulman", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(8, "La responsabilité dépend de la capacité", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(9, "Ne sont acceptées que les bonnes choses", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(10, "Le scrupule", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(11, "Se consacrer aux choses utiles", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(12, "La foi parfaite", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(13, "L'inviolabilité du sang du Musulman", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(14, "Les vertus islamiques", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(15, "La piété et la haute moralité", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(16, "L'aide d'Allah et Sa protection", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(17, "La pudeur", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(18, "Persévérer dans la voie", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(19, "La facilité de la religion", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(20, "Faire assaut de bonnes actions", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(21, "L'interdiction absolue de l'injustice", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(22, "Le sens large de l'aumône", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(23, "La diversité des bonnes œuvres", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(24, "La piété c‟est la haute moralité", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(25, "L'attachement à la Sunna", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(26, "La voie du Paradis", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(27, "Les droits d'Allah", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(28, "La vraie ascèse", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(29, "Tout préjudice est illégal", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(30, "La preuve incombe au demandeur", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(31, "L'empêchement du blâmable est un devoir religieux", 0);
INSERT INTO hadith_title(id, title, `next`) VALUES(32, "La vraie fraternité", 0);


INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(0, 0, "Les actions ne valent que par leurs intentions", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(0, 1, "L'émir des croyants Abû Hafs `Omar Ibn al Khattâb <img class='rad'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(0, 2, "« J'ai entendu l'Envoyé d'Allah <img class='saw'/> dire :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(0, 3, "« Les actes ne valent que par les intentions et à chacun selon son intention", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(0, 4, "Celui qui a accompli l'émigration pour plaire à Allâh et à Son Envoyé", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(0, 5, "son émigration lui sera comptée comme accomplie en vue d'Allah et de Son Envoyé", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(0, 6, "Celui qui l'a accomplie pour obtenir quelques biens en ce bas monde, ou pour épouser une femme", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(0, 7, "son émigration lui sera comptée selon ce qu'il recherchait »", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(0, 8, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 0, "L'Islam, la foi, et la bienfaisance", "Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 1, "D'après `Omar <img class='rad'/> qui a dit :", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 2, "« Un jour, nous étions assis chez le Prophète <img class='saw'/>", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 3, "et voici que se présenta à nous un homme vêtu d'habits d'une blancheur resplendissante et aux cheveux très noirs", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 4, "On ne pouvait distinguer sur lui aucune trace de voyage, alors que personne d'entre nous ne le connaissait", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 5, "Il prit alors place, en face du Prophète <img class='saw'/>", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 6, "Il plaça ses genoux contre les siens, et posa les paumes de ses mains sur les cuisses de celui-ci", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 7, "et lui dit: « Ô Muhammad, informe-moi sur l'Islam »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 8, "« L’Islam », dit le Prophète <img class='saw'/>", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 9, "« c’est que tu témoignes qu’il n'y a pas de Divinité sinon Allah et que Muhammad est l’Envoyé d'Allah", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 10, "que tu accomplisses la prière, que tu donnes l’aumône [Zakât], que tu jeûnes le Ramadan", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 11, "et que tu fasses le pèlerinage de la Maison d'Allah si tu en as la possibilité »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 12, "L'étranger lui répondit: « Tu as dit vrai », et nous nous sommes alors étonnés, tant de sa question que de son approbation", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 13, "puis, il reprit « Informe moi sur la Foi »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 14, "« La foi », dit-il <img class='saw'/>", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 15, "« c’est que tu croies en Allah, en Ses Anges, en Ses Livres, en Ses Envoyés, au Jour Dernier, et que tu croies au destin, qu’il soit bon ou mauvais »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 16, "L'étranger : « Tu as dit la vérité, informe-moi sur le bel-agir », ajouta-t-il", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 17, "« Que tu adores Allah comme si tu Le voyais", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 18, "Et si tu ne Le vois pas, certes Lui te voit lui répondit le Prophète <img class='saw'/>", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 19, "L'étranger : « Informe-moi sur l'Heure (de la résurrection) »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 20, "« Celui qui est interrogé n’en sait pas plus sur elle que celui qui l’interroge », lui répondit-il", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 21, "L'étranger : « Informe-moi sur ses signes précurseurs »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 22, "« Quand la femme donnera naissance à sa propre maîtresse", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 23, "et quand tu verras les vas-nu-pieds, les déguenillés et les gueux, gardiens de bêtes", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 24, "rivaliser dans l’élévation des constructions »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 25, "Puis l'homme s'en alla", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 26, "Je restais un bon bout de temps sans rien demander sur cette affaire", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 27, "puis l'Envoyé de Allah <img class='saw'/> me dit : « Sais-tu qui est venu m’interroger ? »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 28, "Allah et Son Envoyé le savent mieux que moi, lui dis-je", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 29, "« C’est l’Ange Gabriel, Il est venu vous apprendre votre religion » »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(1, 30, "<span class='font-italic'/>Rapporté par Muslim</span>","Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(2, 0, "Les Piliers de l'Islam", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(2, 1, "D'après Abû `Abd ar-Rahman `Abd Allah Ibn `Omar <img class='rad'/> l'Envoyé d'Allah <img class='saw'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(2, 2, "« L'Islam est bâti sur ces cinq piliers", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(2, 3, "1- L'attestation de foi", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(2, 4, "2- L'accomplissement de la prière", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(2, 5, "3- L'acquittement de l'aumône légale", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(2, 6, "4- Le pèlerinage à la Mecque", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(2, 7, "5- Le jeune du mois de Ramadan »", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(2, 8, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 0, "Les dernières œuvres sont déterminantes", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 1, "Abû `Abd ar-Rahmân `Abd Allah ibn Mas`ûd a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 2, "« L'Envoyé d'Allah <img class='saw'/> le Trés véridique, le Trés digne de foi, nous a raconté ce qui suit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 3, "« Certes, chacun de vous, lorsqu'il est créé dans le sein de sa mère est d'abord pendant quarante jours une gouttelette", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 4, "puis devient du sang coagulé pendant une semblable durée de temps", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 5, "puis enfin durant un même laps de temps, devient comme une bouchée de chair", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 6, "là-dessus, l'ange lui est envoyé, qui insuffle l'âme, et il est ordonné à celui-ci d'accomplir quatre commandements", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 7, "à savoir d'inscrire : les moyens de vivre (du nouvel être), le terme de son existence, ses actions, enfin, son infortune, ou son bonheur futur", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 8, "Par Allah, en dehors de Qui il n'est pas d'autre Divinité", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 9, "certes, chacun de vous aurait beau œuvrer comme l'ont fait ceux destinés au Paradis, en sorte qu'il s'en approcherait à la distance d'une coudée", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 10, "alors ce qui a été écrit pour lui prévaudrait, et donc il accomplirait (quand même) les actions des damnés, et il entrerait en Enfer", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 11, "Et certes, chacun de vous aurait beau œuvrer comme les damnés, au point de s'approcher de l'Enfer à la distance d'une coudée", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 12, "alors ce qui a été écrit pour lui prévaudrait, en sorte qu'il accomplirait les actions des élus et qu'il entrerait (quand même) au Paradis »", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(3, 13, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(4, 0, "La nullité des innovations", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(4, 1, "D'après la mère des croyants `Aicha <img class='rad'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(4, 2, "« L'Envoyé d'Allah <img class='saw'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(4, 3, "« Quiconque apporte à notre religion une nouveauté qui n'en provient pas, celui-là est à repousser » »", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(4, 4, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 0, "Le licite et l'illicite", "Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 1, "Abû `Abd Allah an-Nu'mân Ibn Bashîr <img class='rad'/> a dit :", "Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 2, "« J'ai entendu l'Envoyé de Allah <img class='saw'/> dire :", "Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 3, "« Certes, ce qui est permis est évident, et ce qui est interdit est évident aussi", "Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 4, "Mais, entre l'un et l'autre, il y a bien des choses équivoques, que la plupart des gens ne savent pas (distinguer)", "Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 5, "Qui se garde de l'équivoque purifie sa foi et son honneur, mais celui qui y tombe, tombe dans ce qui est défendu", "Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 6, "il est semblable au pâtre qui mène ses troupeaux aux alentours d'un territoire gardé, et alors, bien vite il y fera paître", "Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 7, "Chaque roi ne possède-t-il pas un territoire gardé ? Le champ gardé de Allah, ce sont les choses défendues", "Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 8, "En vérité, il y a dans le corps humain un morceau de chair qui, en bon état, permet au corps tout entier de prospérer", "Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 9, "et qui, en mauvais état, le corrompt en entier, c'est le cœur » »", "Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(5, 10, "<span class='font-italic'/>Rapporté par Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi</span>","Al-Bukhari , Muslim , Abu-Dawud et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(6, 0, "La religion est le bon conseil", "Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(6, 1, "D'après Abû Rouqayya Tamîm ibn Aws ad-Darî <img class='rad'/>, le Prophète <img class='saw'/> a dit :", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(6, 2, "« « La religion, c'est la sincérité »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(6, 3, "« Envers qui ? Demanda-t-on au Prophète <img class='saw'/>", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(6, 4, "Il répondit « Envers Allah, envers Son Livre, envers Son Envoyé, envers les chefs des musulmans, et le commun peuple parmi eux » »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(6, 5, "<span class='font-italic'/>Rapporté par Muslim</span>","Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(7, 0, "Le caractère sacré du Musulman", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(7, 1, "D'après Ibn `Omar <img class='rad'/>, l'Envoyé d'Allah <img class='saw'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(7, 2, "« Il m'a été ordonné de combattre les hommes jusqu'à ce qu'ils témoignent qu'il n'est d'autre divinité qu'Allah", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(7, 3, "et que Mohammed est Son Envoyé", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(7, 4, "qu'ils accomplissent la prière rituelle", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(7, 5, "qu'ils acquittent l’aumône", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(7, 6, "S'ils exécutent ces choses, ils seront, à mon égard, garantis quant à leurs personnes et à leurs richesses", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(7, 7, "à moins qu'ils ne transgressent (ouvertement) la loi de l'Islâm, mais Allah règlera le compte de leurs (intentions vraies) »", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(7, 8, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(8, 0, "La responsabilité dépend de la capacité", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(8, 1, "Abû Hourayra `Abd Rahman Ibn Sakhr <img class='rad'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(8, 2, "« J'ai entendu l'Envoyé d'Allah <img class='saw'/> dire :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(8, 3, "« Ce que je vous ai défendu de faire évitez-le", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(8, 4, "et ce que je vous ai ordonné, accomplissez-le dans la mesure où cela vous est possible", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(8, 5, "Ceux qui vous ont précédé ont péri seulement par l'abondance de leurs questions et leurs divergences d'opinions à l'égard de leurs Prophètes » »", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(8, 6, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 0, "Ne sont acceptées que les bonnes choses", "Muslim et At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 1, "D'après Abu Hurayra <img class='rad'/>, l'Envoyé de Allah <img class='saw'/> a dit :", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 2, "« Allah le Très-Haut est bon et n'accepte que ce qui est bon,", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 3, "sachez qu'Allah a ordonné aux croyants ce qu'il a ordonné aux Envoyés,", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 4, "Il a dit [ s'agissant des Envoyés ] : <span class='arab'>{</span> Ô les Envoyés ! Mangez des choses bonnes, œuvrez salutairement", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 5, "Je sais parfaitement ce que vous faites <span class='arab'>}</span>,", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 6, "et Il a dit [ s'agissant des croyants ] : <span class='arab'>{</span> O vous qui croyez ! Mangez des choses bonnes que Nous vous attribuons <span class='arab'>}</span> »", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 7, "Puis il parla de l'homme qui fait un long voyage, à la tignasse mal peignée, poussiéreux, levant les mains au ciel criant :", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 8, "« Seigneur ! Seigneur », alors que sa nourriture est de source illicite, sa boisson est de source illicite, ses habits sont de source illicite, il s'est rassasié de ce qui est illicite", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 9, "Il est loin pour que son invocation soit exaucée »", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(9, 10, "<span class='font-italic'/>Rapporté par Muslim et At-Tirmidhi</span>","Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(10, 0, "Le scrupule", "At-Tirmidhi et An-Nasa'i", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(10, 1, "Abû Muhammad al Hasan Ibn `Ali <img class='rad'/> a dit :", "At-Tirmidhi et An-Nasa'i", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(10, 2, "« J'ai gardé dans ma mémoire de l'Envoyé d'Allah <img class='saw'/> ces paroles :", "At-Tirmidhi et An-Nasa'i", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(10, 3, "« Renonce à ce qui t'inspire du doute pour ce qui ne t'en inspire pas » »", "At-Tirmidhi et An-Nasa'i", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(10, 4, "<span class='font-italic'/>Rapporté par At-Tirmidhi et An-Nasa'i</span>","At-Tirmidhi et An-Nasa'i", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(11, 0, "Se consacrer aux choses utiles", "At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(11, 1, "Abû Hourayra <img class='rad'/> a dit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(11, 2, "« L'Envoyé d'Allah <img class='saw'/> a dit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(11, 3, "« Parmi les qualités d'un bon Islam, il y a le fait pour l'homme de ne pas s'occuper de ce qui ne le regarde pas » »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(11, 4, "<span class='font-italic'/>Rapporté par At-Tirmidhi</span>","At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(12, 0, "La foi parfaite", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(12, 1, "D'après Abû Hamza Anas ibn Mâlik <img class='rad'/>, le Prophète <img class='saw'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(12, 2, "« Aucun de vous ne devient véritablement croyant s'il ne désire pour son frère, ce qu'il désire pour lui même »", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(12, 3, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(13, 0, "L'inviolabilité du sang du Musulman", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(13, 1, "Ibn Mas`ud <img class='rad'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(13, 2, "« L'Envoyé d'Allah <img class='saw'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(13, 3, "« Il n'est pas licite de faire couler le sang du musulman, sauf s'il s'agit d'un des trois coupables que voici :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(13, 4, "le marié qui commet l’adultère,", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(13, 5, "l’auteur d’un homicide volontaire,", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(13, 6, "et l'apostat qui se sépare de la communauté musulmane » »", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(13, 7, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(14, 0, "Les vertus islamiques", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(14, 1, "D'après Abû Hurayra <img class='rad'/>, l'Envoyé d'Allah <img class='saw'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(14, 2, "« Celui qui croit en Allâh et au Jugement Dernier, qu’il dise une bonne chose ou qu’il se taise", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(14, 3, "Celui qui croit en Allâh et au Jugement Dernier, qu’il fasse du bien à son voisin", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(14, 4, "Celui qui croit en Allâh et au Jugement Dernier, qu’il soit hospitalier à l’égard de son hôte »", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(14, 5, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(15, 0, "La piété et la haute moralité", "At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(15, 1, "D'après Abu Dharr Jundub ibn Junâda et Abu 'abd ar-Rahmân Mu`âdh ibn Jabal <img class='rad'/>, l'Envoyé de Allah <img class='saw'/> a dit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(15, 2, "« Prémunis-toi envers Allah où que tu sois", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(15, 3, "Fais suivre la mauvaise action d'une bonne action, celle-ci l'effacera", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(15, 4, "Comporte-toi avec les gens en faisant preuve d'une haute moralité »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(15, 5, "<span class='font-italic'/>Rapporté par At-Tirmidhi</span>","At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 0, "L'aide d'Allah et Sa protection", "At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 1, "`Abd Allah Ibn `Abbâs <img class='rad'/> a dit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 2, "« J'étais [un jour] derrière le Prophète <img class='saw'/> et il me dit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 3, "« Ô jeune homme, je vais t'enseigner quelques préceptes", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 4, "Observe les commandements d'Allah, il te protègera", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 5, "Observe les commandements d'Allah, tu le trouveras devant toi", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 6, "Lorsque tu as à demander quelque chose, demande à Allah", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 7, "Lorsque tu as à implorer assistance, implore assistance auprès d'Allah", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 8, "Sache que si la communauté est d'accord, à l'unanimité, pour te faire quelque bien,", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 9, "cela ne te profitera que dans la mesure où Allah te l'aurait assigné,", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 10, "et si elle est d'accord à l'unanimité pour te causer quelque tort, tu n'en pâtiras en rien,", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 11, "sinon dans la mesure où Allah en aurait ainsi décidé à ton encontre", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 12, "Certes, les calames sont levés et l'encre des feuillets a séché » »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(16, 13, "<span class='font-italic'/>Rapporté par At-Tirmidhi</span>","At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(17, 0, "La pudeur", "Al-Bukhari", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(17, 1, "Abû Mas`ûd `Uqba Ibn `Amir l'Ansarite le Badrite <img class='rad'/> a dit :", "Al-Bukhari", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(17, 2, "« L'Envoyé d'Allah <img class='saw'/> a dit :", "Al-Bukhari", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(17, 3, "« Certes, de tout ce que les gens saisissent d'antiques paroles prophétiques, la première est :", "Al-Bukhari", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(17, 4, "Si tu n'as pas de pudeur, fais ce que tu veux » »", "Al-Bukhari", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(17, 5, "<span class='font-italic'/>Rapporté par Al-Bukhari</span>","Al-Bukhari", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(18, 0, "Persévérer dans la voie", "Muslim et At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(18, 1, "Soufyân Ibn `Abd Allah <img class='rad'/> a dit :", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(18, 2, "« « Ô Envoyé d'Allah ! Dis-moi une parole touchant l'Islam, telle que je n'interrogerai à son sujet personne d'autre que toi »", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(18, 3, "Il dit « Dis : J'ai foi en Allâh, puis suis la voie droite »", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(18, 4, "<span class='font-italic'/>Rapporté par Muslim et At-Tirmidhi</span>","Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(19, 0, "La facilité de la religion", "Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(19, 1, "`Abd Allah Jâber ibn `Abd Allah <img class='rad'/> rapporte ceci :", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(19, 2, "« A ton avis, si j'accomplis les prières rituelles prescrites, si je jeûne le mois de Ramadân,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(19, 3, "si je m'en tiens aux choses permises et évite ce qui est défendu,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(19, 4, "sans y ajouter aucune autre pratique (surérogatoire) entrerai-je au Paradis ?", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(19, 5, "Le Prophète <img class='saw'/> répondit : Oui »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(19, 6, "<span class='font-italic'/>Rapporté par Muslim</span>","Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 0, "Faire assaut de bonnes actions", "Muslim et At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 1, "D'après Abou Malik al Harith Ibn `Asim al Asha`ri <img class='rad'/>, l'Envoyé d'Allah <img class='saw'/> a dit :", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 2, "« La purification est la moitié de la foi", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 3, "Dire : « Louange à Allah [ Al Hamdulillah ], remplit la balance »", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 4, "Dire : « Gloire à la transcendance d’Allah, louange à Allah [ Subhan Allah, Al Hamdulillah ] »", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 5, "remplit l’espace compris entre le ciel et la terre", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 6, "La prière est lumière", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 7, "L’aumône est une preuve", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 8, "La patience est flamboiement", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 9, "Le Coran est argument en ta faveur ou contre toi", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 10, "Chaque homme part le matin pour faire commerce de son âme, la sauvant, ou la faisant périr »", "Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(20, 11, "<span class='font-italic'/>Rapporté par Muslim et At-Tirmidhi</span>","Muslim et At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 0, "L'interdiction absolue de l'injustice", "Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 1, "Abû Dharr <img class='rad'/> a dit :", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 2, "« Relatant les paroles de son Seigneur, le Prophète <img class='saw'/> a dit :", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 3, "« Ô Mes Serviteurs, je me suis interdit l'injustice et Je vous déclare que Je vous l'interdis", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 4, "Ne soyez donc pas injustes les uns envers les autres", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 5, "Ô Mes Serviteurs, chacun d'entre vous est un égaré, sauf celui que Je mène dans le droit chemin :", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 6, "demandez-Moi donc que Je vous mène, et Je vous y mènerai", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 7, "Ô Mes Serviteurs, chacun d'entre vous est affamé, sauf celui que Je nourris,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 8, "demandez-moi donc de vous nourrir, et Je vous nourrirai", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 9, "Ô Mes serviteurs, chacun d'entre vous est nu, sauf celui que J'habille,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 10, "demandez- Moi donc de vous habiller et Je vous habillerai", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 11, "Ô Mes serviteurs, vous pêchez de nuit comme de jour et Moi Je pardonne tous les péchés,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 12, "demandez- Moi donc de vous pardonner, et Je vous pardonnerai", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 13, "Ô Mes serviteurs, en vain feriez-vous des efforts pour réussir à Me nuire et en vain pour réussir à M'être utiles", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 14, "Ô Mes serviteurs, si du premier au dernier, homme ou génie,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 15, "vous étiez aussi pieux que l'est celui au cœur le plus pur d'entre vous, cela n'ajouterait rien à Mon Royaume", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 16, "Ô Mes Serviteurs, si du premier au dernier homme ou génie,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 17, "vous étiez aussi pervers que l'est celui d'entre vous au cœur le plus pervers, cela ne diminuerait en rien Mon royaume", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 18, "Ô Mes Serviteurs, si du premier au dernier, homme ou génie,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 19, "vous vous teniez dans une seule région de la terre pour solliciter Mes faveurs", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 20, "et si J'accordais à chacun de vous sa demande, cela n'amoindrirait en rien Mes propriétés,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 21, "pas plus que l’aiguille n'enlève quoi que ce soit à l'Océan en y pénétrant", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 22, "Ô Mes serviteurs, ce sont vos actes seulement dont Je tiendrai compte, ensuite", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 23, "Je vous rémunérerai d'après ceux-ci", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 24, "Donc celui qui trouve le bonheur, qu'il rende grâce à Allah", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 25, "et celui qui trouve autre chose, qu'il ne s'en prenne qu'a lui-même »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(21, 26, "<span class='font-italic'/>Rapporté par Muslim</span>","Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 0, "Le sens large de l'aumône", "Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 1, "D'après Abû Dharr <img class='rad'/> quelques compagnons de l'Envoyé d'Allah <img class='saw'/> lui dirent :", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 2, "« Ô Envoyé de Allah, les gens les plus riches ont accaparé les récompenses,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 3, "ils prient comme nous, jeûnent comme nous,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 4, "de plus ils font l'aumône avec le surplus de leurs richesses »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 5, "Il répondit : « Comment Allâh ne vous a pas donné de quoi faire L'aumône ?", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 6, "Dire ‹Subhan Allah› (Gloire à Allah) c'est une aumône,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 7, "‹Allâh u akbar› (Allah est Grand), c'est une aumone aussi,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 8, "et de même : Al Hamdulillah (Louanges à Allah), Lâ ilaha illa-l-Allah (Il n'y a d'autre divinité qu'Allâh›)", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 9, "Chaque fois que vous ordonnez le bien, c'est une aumône,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 10, "et chaque fois que vous défendez le mal, c'est une aumône", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 11, "Chaque fois que vous faites œuvre de chair, vous faites une aumône »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 12, "Ils s'écrièrent alors : « Comment, chacun de nous satisferait ses appétits charnels et mériterait par là une rétribution ? »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 13, "Il répondit : « Voyons, celui qui assouvit ses appétits de façons illicite, ne se charge-t-il pas d'un péché ?", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 14, "De même celui qui les satisfait de façon licite, obtient une rétribution »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(22, 15, "<span class='font-italic'/>Rapporté par Muslim</span>","Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(23, 0, "La diversité des bonnes œuvres", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(23, 1, "Abû Hourayra <img class='rad'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(23, 2, "« L'Envoyé d'Allah <img class='saw'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(23, 3, "« L'homme a, sur chaque articulation, une aumône", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(23, 4, "Chaque jour où le soleil se lève et où tu réconcilies deux adversaires, tu fais une aumône", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(23, 5, "En aidant un homme soit à enfourcher sa monture, soit à y placer sa marchandise, tu fais une aumône", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(23, 6, "Une bonne parole, c'est une aumône,", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(23, 7, "chaque pas que tu fais pour te rendre à la prière rituelle, c'est une aumône,", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(23, 8, "en écartant un obstacle du chemin, tu fais une aumône »", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(23, 9, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 0, "La piété c‟est la haute moralité", "At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 1, "D'après An-Nawwâs ibn Sam'an <img class='rad'/>, le Prophète <img class='saw'/> a dit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 2, "« La Piété consiste en la haute moralité,", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 3, "le mal est ce qui met ton âme dans l’embarras et qu’il te répugne que les gens le découvrent en toi »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 4, "Wâbiça ben Mabad (que Allah soit satisfait de lui) a dit : j'allais voir l'Envoyé d'Allah et il me dit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 5, "« Tu viens me questionner au sujet de la vertu ? »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 6, "« Oui », répondis-je, et il reprit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 7, "« Interroge ton cœur", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 8, "La vertu c'est ce par quoi l'âme jouit du repos et le cœur de la tranquillité", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 9, "Le péché, c'est ce qui s'implante dans l'âme et met le trouble au sein de l'homme,", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 10, "et ceci malgré toutes les consultations religieuses que l'on pourrait te donner (pour te tranquilliser)»", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(24, 11, "<span class='font-italic'/>Rapporté par At-Tirmidhi</span>","At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 0, "L'attachement à la Sunna", "At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 1, "Abû al Irbad ibn Sâriya <img class='rad'/> a dit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 2, "« L'Envoyé d'Allah <img class='saw'/> nous fit un jour un prêche qui fit frémir les cœurs et couler les larmes des yeux", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 3, "Nous lui dimes alors :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 4, "« Ô Envoyé de Allah, on dirait un sermon d'aAllahx", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 5, "Faites-nous une (dernière) recommandation »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 6, "Il répondit : « Je vous recommande d'adorer Allâh (que sa gloire et Sa puissance soient exaltées),", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 7, "d'écouter votre chef, et de lui obéir, votre Emîr fut-il un esclave", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 8, "Certes, qui de vous vivra, verra de graves discordes", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 9, "Il vous incombe donc de suivre ma manière d'être et celle des Califes bien guidés", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 10, "Tenez-vous à cela de toutes vos forces, et gardez-vous des nouveautés religieuses, car toute innovation est égarement »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(25, 11, "<span class='font-italic'/>Rapporté par At-Tirmidhi</span>","At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 0, "La voie du Paradis", "At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 1, "Mou`adh Ibn Jabal <img class='rad'/> rapporte :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 2, "« Je dis : « Ô Envoyé d'Allah, enseigne-moi une œuvre qui me fera entrer au Paradis et qui m’éloignera du Feu »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 3, "Tu adores Allah sans rien Lui associer,", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 4, "tu accomplis la prière,", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 5, "tu t’acquittes de l’aumône légale [ zakât ],", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 6, "tu jeûnes le mois de Ramâdan", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 7, "et tu fais le pèlerinage »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 8, "Puis le prophète poursuivit", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 9, "« Veux-tu que je te montre les portes du Bien ?", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 10, "Le jeûne est un rempart", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 11, "L'aumône éteint le péché comme l'eau éteint le feu", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 12, "La prière de l'homme au milieu de la nuit (Est la meilleure) »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 13, "Puis il récita le verset : <span class='arab'>{</span> Eux qui détachent leurs flancs de leur lit, pour invoquer leur Seigneur,", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 14, "dans la crainte et l’espoir, et sur notre attribution fait dépense", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 15, "Nulle âme ne peut connaître ce qu’on a réservé pour eux comme fraîcheur des yeux, en récompense de ce qu’ils pratiquaient", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 16, "<span class='arab'>}</span> (32:16-17)", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 17, "Puis il reprit : « Veux -tu que je te montre la partie principale de la religion, sa colonne et son sommet ? »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 18, "« Oui, Ô Envoyé d'Allah », répondis je", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 19, "Il répondit : « La partie principale de la religion, c'est la soumission à Allah,", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 20, "sa colonne, c'est la prière rituelle,", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 21, "et son sommet, la guerre sainte »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 22, "Il ajouta : « Veux-tu que je t'apprenne ce qui soutient tout cela ? »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 23, "« Oui, Ô Envoyé d'Allah », répondis-je", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 24, "Il saisit alors sa propre langue et dit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 25, "« Garde-toi de celle-là »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 26, "Je lui dis : « Ô Prophète d'Allah, serons-nous donc susceptibles d'être châtiés pour avoir parlé ? »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 27, "Il me répondit : « Malheureux, qu’est-ce qui fait tomber les gens en Enfer, face en avant, (ou sur leur nez) si ce n'est ce que leur langue profère ? »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 28, " Il me répondit : « Malheureux, qu’est-ce qui fait tomber les gens en Enfer, face en avant, (ou sur leur nez) si ce n'est ce que leur langue profère ? »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 29, "Il répondit : « Tu viens d’interroger sur une affaire énorme qui est pourtant aisée pour qui Allah le Très-Haut l’a rendue aisée :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(26, 30, "<span class='font-italic'/>Rapporté par At-Tirmidhi</span>","At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(27, 0, "Les droits d'Allah", "At-Tirmidhi", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(27, 1, "D'après Abû Tha'laba al Khushanî <img class='rad'/>, l'Envoyé d'Allah <img class='saw'/> a dit :", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(27, 2, "« Certes, Allah, Trés Haut, a fixé des obligations canoniques, ne les négligez pas;", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(27, 3, "il a déterminé des limites, ne les transgressez pas;", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(27, 4, "il a interdit certaines choses, n'en usez pas;", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(27, 5, "il s'est tu à propos d'autres, par miséricorde à votre égard, non par oubli, n'en scrutez donc pas les raisons »", "At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(27, 6, "<span class='font-italic'/>Rapporté par At-Tirmidhi</span>","At-Tirmidhi", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(28, 0, "La vraie ascèse", "Ibn Maja", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(28, 1, "Abû l-`Abbas Sahl Ibn Sa`d As-Sa`idi <img class='rad'/> rapporte :", "Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(28, 2, "« Un homme vint dire au Prophète <img class='saw'/>", "Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(28, 3, "« Envoyé d'Allah, montre-moi une œuvre que si je la fais, Allah m'aimera et les gens m'aimeront aussi »", "Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(28, 4, "Il lui dit <img class='saw'/> :", "Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(28, 5, "« Mène une vie de tempérance, Allah t’aimera ;", "Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(28, 6, "renonce à ce que possèdent les gens, les gens t’aimeront » »", "Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(28, 7, "<span class='font-italic'/>Rapporté par Ibn Maja</span>","Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(29, 0, "Tout préjudice est illégal", "Ibn Maja", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(29, 1, "D'après Abû Sa'id Ibn Malik Ibn Sinân al Khudri <img class='rad'/>", "Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(29, 2, "L'Envoyé d'Allah <img class='saw'/> a dit :", "Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(29, 3, "« Tout préjudice est illégal : qu’il soit involontaire ou volontaire »", "Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(29, 4, "<span class='font-italic'/>Rapporté par Ibn Maja</span>","Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(30, 0, "La preuve incombe au demandeur", "Al-Bukhari et Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(30, 1, "D'Après Ibn `Abbas <img class='rad'/>,", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(30, 2, "l'Envoyé d'Allah <img class='saw'/> a dit :", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(30, 3, "« Si l’on reconnaissait aux hommes le bien fondé de toutes leurs prétentions,", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(30, 4, "les uns ne manqueraient certes pas de revendiquer les bien et la vie des autres;", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(30, 5, "mais le demandeur est tenu de fournir la preuve", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(30, 6, "et le serment est imposé à celui qui nie la chose»", "Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(30, 7, "<span class='font-italic'/>Rapporté par Al-Bukhari et Muslim</span>","Al-Bukhari et Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(31, 0, "L'empêchement du blâmable est un devoir religieux", "Muslim , Abu-Dawud , An-Nasa'i et Ibn Maja", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(31, 1, "Abû Sa`id al Kudri <img class='rad'/> a dit :", "Muslim , Abu-Dawud , An-Nasa'i et Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(31, 2, "J'ai entendu l'Envoyé d'Allah <img class='saw'/> dire :", "Muslim , Abu-Dawud , An-Nasa'i et Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(31, 3, "« Quiconque constate un fait blâmable doit intervenir pour le corriger par la main,", "Muslim , Abu-Dawud , An-Nasa'i et Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(31, 4, "s’il n’est pas capable qu’il le fasse par la langue,", "Muslim , Abu-Dawud , An-Nasa'i et Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(31, 5, "s’il n’en est pas capable qu’il le désapprouve en son for intérieur,", "Muslim , Abu-Dawud , An-Nasa'i et Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(31, 6, "c’est là le degré le plus faible de la foi »", "Muslim , Abu-Dawud , An-Nasa'i et Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(31, 7, "<span class='font-italic'/>Rapporté par Muslim , Abu-Dawud , An-Nasa'i et Ibn Maja</span>","Muslim , Abu-Dawud , An-Nasa'i et Ibn Maja", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 0, "La vraie fraternité", "Muslim", 1);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 1, "D'après Abû Hourayra <img class='rad'/>,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 2, "l'Envoyé d'Allah <img class='saw'/> a dit :", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 3, "« Ne vous enviez pas les uns les autres,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 4, "que les uns ne fassent pas monter le prix d’une marchandise sur les prix des autres sans l’intention de l’acheter [najash],", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 5, "ne vous haïssez pas, ne vous tournez pas le dos les uns des autres,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 6, "que les uns ne pratiquent pas des ventes sur les ventes des autres", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 7, "Soyez des serviteurs d’Allah qui sont frères, le musulman est le frère du musulman,", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 8, "il ne lui fait pas d’injustice et ne lui refuse pas son soutien ni ne lui ment et ne le méprise pas", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 9, "La piété est ici – désignant sa poitrine trois fois -", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 10, "Il suffit à l’homme, pour être mauvais, de mépriser son frère musulman", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 11, "Tout le musulman est interdit au musulman : son sang, ses biens et son honneur »", "Muslim", 0);
INSERT INTO hadith(id_hadith_title, id_line, french, report, is_title) VALUES(32, 12, "<span class='font-italic'/>Rapporté par Muslim</span>","Muslim", 0);